# Screen
WIDTH = 620
HEIGHT = 405
EDGE_LR = WIDTH / 2 - 12
EDGE_TB = HEIGHT / 2 - 12

# Bricks
COLUMNS = 10
STRETCH = 3
COLORS = ["alice blue", "AliceBlue", "antique white", "AntiqueWhite", "AntiqueWhite1", "AntiqueWhite2", "AntiqueWhite3",
          "AntiqueWhite4", "aquamarine", "aquamarine1", "aquamarine2", "aquamarine3", "aquamarine4", "azure", "azure1",
          "azure2", "azure3", "azure4", "beige", "bisque", "bisque1", "bisque2", "bisque3", "bisque4", "black",
          "blanched almond", "BlanchedAlmond", "blue", "blue violet", "blue1", "blue2", "blue3", "blue4", "BlueViolet",
          "brown", "brown1", "brown2", "brown3", "brown4", "burlywood", "burlywood1", "burlywood2", "burlywood3",
          "burlywood4", "cadet blue", "CadetBlue", "CadetBlue1", "CadetBlue2", "CadetBlue3", "CadetBlue4", "chartreuse",
          "chartreuse1", "chartreuse2", "chartreuse3", "chartreuse4", "chocolate", "chocolate1", "chocolate2",
          "chocolate3", "chocolate4", "coral", "coral1", "coral2", "coral3", "coral4", "cornflower blue",
          "CornflowerBlue", "cornsilk", "cornsilk1", "cornsilk2", "cornsilk3", "cornsilk4", "cyan", "cyan1", "cyan2",
          "cyan3", "cyan4", "dark blue", "dark cyan", "dark goldenrod", "dark gray", "dark green", "dark grey",
          "dark khaki", "dark magenta", "dark olive green", "dark orange", "dark orchid", "dark red", "dark salmon",
          "dark sea green", "dark slate blue", "dark slate gray", "dark slate grey", "dark turquoise", "dark violet",
          "DarkBlue", "DarkCyan", "DarkGoldenrod", "DarkGoldenrod1", "DarkGoldenrod2", "DarkGoldenrod3",
          "DarkGoldenrod4", "DarkGray", "DarkGreen", "DarkGrey", "DarkKhaki", "DarkMagenta", "DarkOliveGreen",
          "DarkOliveGreen1", "DarkOliveGreen2", "DarkOliveGreen3", "DarkOliveGreen4", "DarkOrange", "DarkOrange1",
          "DarkOrange2", "DarkOrange3", "DarkOrange4", "DarkOrchid", "DarkOrchid1", "DarkOrchid2", "DarkOrchid3",
          "DarkOrchid4", "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSeaGreen1", "DarkSeaGreen2", "DarkSeaGreen3",
          "DarkSeaGreen4", "DarkSlateBlue", "DarkSlateGray", "DarkSlateGray1", "DarkSlateGray2", "DarkSlateGray3",
          "DarkSlateGray4", "DarkSlateGrey", "DarkTurquoise", "DarkViolet", "deep pink", "deep sky blue", "DeepPink",
          "DeepPink1", "DeepPink2", "DeepPink3", "DeepPink4", "DeepSkyBlue", "DeepSkyBlue1", "DeepSkyBlue2",
          "DeepSkyBlue3", "DeepSkyBlue4", "dim gray", "dim grey", "DimGray", "DimGrey", "dodger blue", "DodgerBlue",
          "DodgerBlue1", "DodgerBlue2", "DodgerBlue3", "DodgerBlue4", "firebrick", "firebrick1", "firebrick2",
          "firebrick3", "firebrick4", "floral white", "FloralWhite", "forest green", "ForestGreen", "gainsboro",
          "ghost white", "GhostWhite", "gold", "gold1", "gold2", "gold3", "gold4", "goldenrod", "goldenrod1",
          "goldenrod2", "goldenrod3", "goldenrod4", "gray", "gray0", "gray1", "gray10", "gray100", "gray11", "gray12",
          "gray13", "gray14", "gray15", "gray16", "gray17", "gray18", "gray19", "gray2", "gray20", "gray21", "gray22",
          "gray23", "gray24", "gray25", "gray26", "gray27", "gray28", "gray29", "gray3", "gray30", "gray31", "gray32",
          "gray33", "gray34", "gray35", "gray36", "gray37", "gray38", "gray39", "gray4", "gray40", "gray41", "gray42",
          "gray43", "gray44", "gray45", "gray46", "gray47", "gray48", "gray49", "gray5", "gray50", "gray51", "gray52",
          "gray53", "gray54", "gray55", "gray56", "gray57", "gray58", "gray59", "gray6", "gray60", "gray61", "gray62",
          "gray63", "gray64", "gray65", "gray66", "gray67", "gray68", "gray69", "gray7", "gray70", "gray71", "gray72",
          "gray73", "gray74", "gray75", "gray76", "gray77", "gray78", "gray79", "gray8", "gray80", "gray81", "gray82",
          "gray83", "gray84", "gray85", "gray86", "gray87", "gray88", "gray89", "gray9", "gray90", "gray91", "gray92",
          "gray93", "gray94", "gray95", "gray96", "gray97", "gray98", "gray99", "green", "green yellow", "green1",
          "green2", "green3", "green4", "GreenYellow", "grey", "grey0", "grey1", "grey10", "grey100", "grey11",
          "grey12", "grey13", "grey14", "grey15", "grey16", "grey17", "grey18", "grey19", "grey2", "grey20", "grey21",
          "grey22", "grey23", "grey24", "grey25", "grey26", "grey27", "grey28", "grey29", "grey3", "grey30", "grey31",
          "grey32", "grey33", "grey34", "grey35", "grey36", "grey37", "grey38", "grey39", "grey4", "grey40", "grey41",
          "grey42", "grey43", "grey44", "grey45", "grey46", "grey47", "grey48", "grey49", "grey5", "grey50", "grey51",
          "grey52", "grey53", "grey54", "grey55", "grey56", "grey57", "grey58", "grey59", "grey6", "grey60", "grey61",
          "grey62", "grey63", "grey64", "grey65", "grey66", "grey67", "grey68", "grey69", "grey7", "grey70", "grey71",
          "grey72", "grey73", "grey74", "grey75", "grey76", "grey77", "grey78", "grey79", "grey8", "grey80", "grey81",
          "grey82", "grey83", "grey84", "grey85", "grey86", "grey87", "grey88", "grey89", "grey9", "grey90", "grey91",
          "grey92", "grey93", "grey94", "grey95", "grey96", "grey97", "grey98", "grey99", "honeydew", "honeydew1",
          "honeydew2", "honeydew3", "honeydew4", "hot pink", "HotPink", "HotPink1", "HotPink2", "HotPink3", "HotPink4",
          "indian red", "IndianRed", "IndianRed1", "IndianRed2", "IndianRed3", "IndianRed4", "ivory", "ivory1",
          "ivory2", "ivory3", "ivory4", "khaki", "khaki1", "khaki2", "khaki3", "khaki4", "lavender", "lavender blush",
          "LavenderBlush", "LavenderBlush1", "LavenderBlush2", "LavenderBlush3", "LavenderBlush4", "lawn green",
          "LawnGreen", "lemon chiffon", "LemonChiffon", "LemonChiffon1", "LemonChiffon2", "LemonChiffon3",
          "LemonChiffon4", "light blue", "light coral", "light cyan", "light goldenrod", "light goldenrod yellow",
          "light gray", "light green", "light grey", "light pink", "light salmon", "light sea green", "light sky blue",
          "light slate blue", "light slate gray", "light slate grey", "light steel blue", "light yellow", "LightBlue",
          "LightBlue1", "LightBlue2", "LightBlue3", "LightBlue4", "LightCoral", "LightCyan", "LightCyan1", "LightCyan2",
          "LightCyan3", "LightCyan4", "LightGoldenrod", "LightGoldenrod1", "LightGoldenrod2", "LightGoldenrod3",
          "LightGoldenrod4", "LightGoldenrodYellow", "LightGray", "LightGreen", "LightGrey", "LightPink", "LightPink1",
          "LightPink2", "LightPink3", "LightPink4", "LightSalmon", "LightSalmon1", "LightSalmon2", "LightSalmon3",
          "LightSalmon4", "LightSeaGreen", "LightSkyBlue", "LightSkyBlue1", "LightSkyBlue2", "LightSkyBlue3",
          "LightSkyBlue4", "LightSlateBlue", "LightSlateGray", "LightSlateGrey", "LightSteelBlue", "LightSteelBlue1",
          "LightSteelBlue2", "LightSteelBlue3", "LightSteelBlue4", "LightYellow", "LightYellow1", "LightYellow2",
          "LightYellow3", "LightYellow4", "lime green", "LimeGreen", "linen", "magenta", "magenta1", "magenta2",
          "magenta3", "magenta4", "maroon", "maroon1", "maroon2", "maroon3", "maroon4", "medium aquamarine",
          "medium blue", "medium orchid", "medium purple", "medium sea green", "medium slate blue",
          "medium spring green", "medium turquoise", "medium violet red", "MediumAquamarine", "MediumBlue",
          "MediumOrchid", "MediumOrchid1", "MediumOrchid2", "MediumOrchid3", "MediumOrchid4", "MediumPurple",
          "MediumPurple1", "MediumPurple2", "MediumPurple3", "MediumPurple4", "MediumSeaGreen", "MediumSlateBlue",
          "MediumSpringGreen", "MediumTurquoise", "MediumVioletRed", "midnight blue", "MidnightBlue", "mint cream",
          "MintCream", "misty rose", "MistyRose", "MistyRose1", "MistyRose2", "MistyRose3", "MistyRose4", "moccasin",
          "navajo white", "NavajoWhite", "NavajoWhite1", "NavajoWhite2", "NavajoWhite3", "NavajoWhite4", "navy",
          "navy blue", "NavyBlue", "old lace", "OldLace", "olive drab", "OliveDrab", "OliveDrab1", "OliveDrab2",
          "OliveDrab3", "OliveDrab4", "orange", "orange red", "orange1", "orange2", "orange3", "orange4", "OrangeRed",
          "OrangeRed1", "OrangeRed2", "OrangeRed3", "OrangeRed4", "orchid", "orchid1", "orchid2", "orchid3", "orchid4",
          "pale goldenrod", "pale green", "pale turquoise", "pale violet red", "PaleGoldenrod", "PaleGreen",
          "PaleGreen1", "PaleGreen2", "PaleGreen3", "PaleGreen4", "PaleTurquoise", "PaleTurquoise1", "PaleTurquoise2",
          "PaleTurquoise3", "PaleTurquoise4", "PaleVioletRed", "PaleVioletRed1", "PaleVioletRed2", "PaleVioletRed3",
          "PaleVioletRed4", "papaya whip", "PapayaWhip", "peach puff", "PeachPuff", "PeachPuff1", "PeachPuff2",
          "PeachPuff3", "PeachPuff4", "peru", "pink", "pink1", "pink2", "pink3", "pink4", "plum", "plum1", "plum2",
          "plum3", "plum4", "powder blue", "PowderBlue", "purple", "purple1", "purple2", "purple3", "purple4", "red",
          "red1", "red2", "red3", "red4", "rosy brown", "RosyBrown", "RosyBrown1", "RosyBrown2", "RosyBrown3",
          "RosyBrown4", "royal blue", "RoyalBlue", "RoyalBlue1", "RoyalBlue2", "RoyalBlue3", "RoyalBlue4",
          "saddle brown", "SaddleBrown", "salmon", "salmon1", "salmon2", "salmon3", "salmon4", "sandy brown",
          "SandyBrown", "sea green", "SeaGreen", "SeaGreen1", "SeaGreen2", "SeaGreen3", "SeaGreen4", "seashell",
          "seashell1", "seashell2", "seashell3", "seashell4", "sienna", "sienna1", "sienna2", "sienna3", "sienna4",
          "sky blue", "SkyBlue", "SkyBlue1", "SkyBlue2", "SkyBlue3", "SkyBlue4", "slate blue", "slate gray",
          "slate grey", "SlateBlue", "SlateBlue1", "SlateBlue2", "SlateBlue3", "SlateBlue4", "SlateGray", "SlateGray1",
          "SlateGray2", "SlateGray3", "SlateGray4", "SlateGrey", "snow", "snow1", "snow2", "snow3", "snow4",
          "spring green", "SpringGreen", "SpringGreen1", "SpringGreen2", "SpringGreen3", "SpringGreen4", "steel blue",
          "SteelBlue", "SteelBlue1", "SteelBlue2", "SteelBlue3", "SteelBlue4", "tan", "tan1", "tan2", "tan3", "tan4",
          "thistle", "thistle1", "thistle2", "thistle3", "thistle4", "tomato", "tomato1", "tomato2", "tomato3",
          "tomato4", "turquoise", "turquoise1", "turquoise2", "turquoise3", "turquoise4", "violet", "violet red",
          "VioletRed", "VioletRed1", "VioletRed2", "VioletRed3", "VioletRed4", "wheat", "wheat1", "wheat2", "wheat3",
          "wheat4", "white", "white smoke", "WhiteSmoke", "yellow", "yellow green", "yellow1", "yellow2", "yellow3",
          "yellow4", "YellowGreen"]
COLORS_BRIGHTNESS = ["gray100", "grey100", "white", "gray99", "grey99", "snow", "snow1", "ghost white", "GhostWhite",
                     "ivory",
                     "ivory1", "gray98", "grey98", "mint cream", "MintCream", "azure", "azure1", "floral white",
                     "FloralWhite",
                     "alice blue", "AliceBlue", "gray97", "grey97", "lavender blush", "LavenderBlush", "LavenderBlush1",
                     "seashell", "seashell1", "thistle1", "gray96", "grey96", "white smoke", "WhiteSmoke", "honeydew",
                     "honeydew1",
                     "light yellow", "LightYellow", "LightYellow1", "light cyan", "LightCyan", "LightCyan1", "old lace",
                     "OldLace",
                     "gray95", "grey95", "cornsilk", "cornsilk1", "linen", "gray94", "grey94", "AntiqueWhite1",
                     "gray93", "grey93",
                     "lemon chiffon", "LemonChiffon", "LemonChiffon1", "light goldenrod yellow", "LightGoldenrodYellow",
                     "beige",
                     "lavender", "misty rose", "MistyRose", "MistyRose1", "papaya whip", "PapayaWhip", "gray92",
                     "grey92", "snow2",
                     "antique white", "AntiqueWhite", "ivory2", "azure2", "plum1", "PaleTurquoise1", "gray91", "grey91",
                     "blanched almond", "BlanchedAlmond", "LavenderBlush2", "seashell2", "gray90", "grey90", "thistle2",
                     "honeydew2", "LightYellow2", "LightCyan2", "LightBlue1", "LightSteelBlue1", "gray89", "grey89",
                     "bisque",
                     "bisque1", "SlateGray1", "cornsilk2", "wheat1", "gray88", "grey88", "gray87", "grey87",
                     "AntiqueWhite2",
                     "moccasin", "LemonChiffon2", "MistyRose2", "DarkSlateGray1", "gainsboro", "peach puff",
                     "PeachPuff",
                     "PeachPuff1", "gray86", "grey86", "LightSkyBlue1", "CadetBlue1", "gray85", "grey85",
                     "pale turquoise",
                     "PaleTurquoise", "navajo white", "NavajoWhite", "NavajoWhite1", "pink", "plum2", "PaleTurquoise2",
                     "wheat",
                     "khaki1", "gray84", "grey84", "RosyBrown1", "DarkSeaGreen1", "pale goldenrod", "PaleGoldenrod",
                     "LightBlue2",
                     "orchid1", "gray83", "grey83", "LightSteelBlue2", "bisque2", "SlateGray2", "pink1", "light gray",
                     "light grey", "LightGray", "LightGrey", "LightGoldenrod1", "light pink", "LightPink",
                     "powder blue",
                     "PowderBlue", "wheat2", "gray82", "grey82", "thistle", "burlywood1", "gray81", "grey81",
                     "light blue",
                     "LightBlue", "DarkSlateGray2", "LightPink1", "PeachPuff2", "LightSkyBlue2", "gray80", "grey80",
                     "khaki",
                     "CadetBlue2", "snow3", "NavajoWhite2", "violet", "ivory3", "gray79", "grey79", "azure3", "plum",
                     "khaki2",
                     "RosyBrown2", "DarkSeaGreen2", "gray78", "grey78", "SkyBlue1", "LavenderBlush3",
                     "light steel blue",
                     "LightSteelBlue", "aquamarine", "aquamarine1", "orchid2", "seashell3", "pink2", "thistle3",
                     "honeydew3",
                     "light sky blue", "LightSkyBlue", "LightYellow3", "LightCyan3", "light goldenrod",
                     "LightGoldenrod",
                     "LightGoldenrod2", "gray77", "grey77", "cornsilk3", "gray76", "grey76", "MediumOrchid1",
                     "burlywood2",
                     "sky blue", "SkyBlue", "LightPink2", "AntiqueWhite3", "gray75", "grey75", "LemonChiffon3", "gray",
                     "grey",
                     "MistyRose3", "DarkOliveGreen1", "gray74", "grey74", "PaleGreen1", "plum3", "PaleTurquoise3",
                     "gray73",
                     "grey73", "PaleVioletRed1", "MediumPurple1", "SkyBlue2", "pale green", "PaleGreen", "aquamarine2",
                     "gray72",
                     "grey72", "LightBlue3", "LightSteelBlue3", "bisque3", "SlateGray3", "HotPink1", "orchid", "gray71",
                     "grey71",
                     "MediumOrchid2", "burlywood", "wheat3", "hot pink", "HotPink", "SteelBlue1", "light salmon",
                     "LightSalmon",
                     "LightSalmon1", "gray70", "grey70", "DarkSlateGray3", "tan", "DarkOliveGreen2", "PeachPuff3",
                     "gray69",
                     "grey69", "LightSkyBlue3", "light green", "LightGreen", "PaleGreen2", "CadetBlue3", "NavajoWhite3",
                     "gray68",
                     "grey68", "PaleVioletRed2", "khaki3", "MediumPurple2", "RosyBrown3", "DarkSeaGreen3", "gray67",
                     "grey67",
                     "HotPink2", "orchid3", "yellow", "yellow1", "magenta", "magenta1", "cyan", "cyan1", "OliveDrab1",
                     "pink3",
                     "DarkOrchid1", "LightGoldenrod3", "dark gray", "dark grey", "DarkGray", "DarkGrey", "dark salmon",
                     "DarkSalmon", "sandy brown", "SandyBrown", "gray66", "grey66", "SteelBlue2", "LightSalmon2",
                     "salmon1",
                     "burlywood3", "turquoise1", "tan1", "light slate blue", "LightSlateBlue", "gray65", "grey65",
                     "SeaGreen1",
                     "SlateBlue1", "light coral", "LightCoral", "turquoise", "LightPink3", "salmon", "gray64", "grey64",
                     "maroon1",
                     "cornflower blue", "CornflowerBlue", "goldenrod1", "medium turquoise", "MediumTurquoise", "gray63",
                     "grey63",
                     "medium orchid", "MediumOrchid", "dark khaki", "DarkKhaki", "SkyBlue3", "pale violet red",
                     "PaleVioletRed",
                     "medium purple", "MediumPurple", "aquamarine3", "medium aquamarine", "MediumAquamarine", "yellow2",
                     "magenta2", "cyan2", "OliveDrab2", "green yellow", "GreenYellow", "rosy brown", "RosyBrown",
                     "DarkOrchid2",
                     "gray62", "grey62", "dark sea green", "DarkSeaGreen", "gold", "gold1", "gray61", "grey61",
                     "IndianRed1",
                     "VioletRed1", "MediumOrchid3", "turquoise2", "salmon2", "tan2", "medium slate blue",
                     "MediumSlateBlue",
                     "SeaGreen2", "SlateBlue2", "coral", "gray60", "grey60", "purple1", "DarkOliveGreen3", "sienna1",
                     "DarkGoldenrod1", "coral1", "maroon2", "PaleGreen3", "goldenrod2", "gray59", "grey59",
                     "MediumPurple3",
                     "deep sky blue", "DeepSkyBlue", "DeepSkyBlue1", "HotPink3", "RoyalBlue1", "gray58", "grey58",
                     "gold2",
                     "IndianRed2", "VioletRed2", "PaleVioletRed3", "gray57", "grey57", "LightSalmon3", "purple",
                     "SteelBlue3",
                     "gray56", "grey56", "dodger blue", "DodgerBlue", "DodgerBlue1", "purple2", "tomato", "tomato1",
                     "DarkGoldenrod2", "sienna2", "coral2", "deep pink", "DeepPink", "DeepPink1", "orange", "orange1",
                     "gray55",
                     "grey55", "chocolate1", "DeepSkyBlue2", "goldenrod", "RoyalBlue2", "dark turquoise",
                     "DarkTurquoise",
                     "gray54", "grey54", "snow4", "cadet blue", "CadetBlue", "yellow3", "magenta3", "cyan3",
                     "OliveDrab3",
                     "yellow green", "YellowGreen", "DarkOrchid3", "ivory4", "azure4", "light slate gray",
                     "light slate grey",
                     "LightSlateGray", "LightSlateGrey", "dark orchid", "DarkOrchid", "blue violet", "BlueViolet",
                     "gray53",
                     "grey53", "LavenderBlush4", "medium spring green", "MediumSpringGreen", "seashell4", "turquoise3",
                     "peru",
                     "tan3", "salmon3", "thistle4", "honeydew4", "slate blue", "SlateBlue", "LightYellow4",
                     "LightCyan4",
                     "SeaGreen3", "DodgerBlue2", "gray52", "grey52", "SlateBlue3", "tomato2", "dark orange",
                     "DarkOrange",
                     "cornsilk4", "royal blue", "RoyalBlue", "DeepPink2", "orange2", "maroon3", "AntiqueWhite4",
                     "gray51",
                     "grey51", "chocolate2", "goldenrod3", "indian red", "IndianRed", "LemonChiffon4", "MistyRose4",
                     "violet red",
                     "VioletRed", "slate gray", "slate grey", "SlateGray", "SlateGrey", "brown1", "DarkOrange1",
                     "chartreuse",
                     "chartreuse1", "spring green", "SpringGreen", "SpringGreen1", "gray50", "grey50", "plum4",
                     "PaleTurquoise4",
                     "steel blue", "SteelBlue", "light sea green", "LightSeaGreen", "gold3", "lawn green", "LawnGreen",
                     "IndianRed3", "VioletRed3", "gray49", "grey49", "LightBlue4", "LightSteelBlue4", "bisque4",
                     "SlateGray4",
                     "purple3", "wheat4", "DarkGoldenrod3", "sienna3", "gray48", "grey48", "coral3", "gray47", "grey47",
                     "DarkSlateGray4", "dark violet", "DarkViolet", "PeachPuff4", "DeepSkyBlue3", "LightSkyBlue4",
                     "RoyalBlue3",
                     "DarkOrange2", "brown2", "chartreuse2", "CadetBlue4", "SpringGreen2", "NavajoWhite4",
                     "medium violet red",
                     "MediumVioletRed", "medium sea green", "MediumSeaGreen", "firebrick1", "khaki4", "gray46",
                     "grey46",
                     "RosyBrown4", "DarkSeaGreen4", "orchid4", "pink4", "chocolate", "gray45", "grey45", "DodgerBlue3",
                     "LightGoldenrod4", "tomato3", "DeepPink3", "burlywood4", "orange3", "chocolate3", "gray44",
                     "grey44",
                     "LightPink4", "gray43", "grey43", "dark goldenrod", "DarkGoldenrod", "firebrick2", "SkyBlue4",
                     "orange red",
                     "OrangeRed", "OrangeRed1", "aquamarine4", "gray42", "grey42", "maroon", "MediumOrchid4",
                     "dim gray",
                     "dim grey", "DimGray", "DimGrey", "gray41", "grey41", "DarkOliveGreen4", "DarkOrange3", "brown3",
                     "chartreuse3", "PaleGreen4", "SpringGreen3", "gray40", "grey40", "lime green", "LimeGreen",
                     "PaleVioletRed4",
                     "MediumPurple4", "OrangeRed2", "gray39", "grey39", "HotPink4", "SteelBlue4", "LightSalmon4",
                     "gray38",
                     "grey38", "sienna", "olive drab", "OliveDrab", "gray37", "grey37", "firebrick3", "yellow4",
                     "dark magenta",
                     "DarkMagenta", "magenta4", "OliveDrab4", "cyan4", "dark cyan", "DarkCyan", "DarkOrchid4", "gray36",
                     "grey36",
                     "turquoise4", "tan4", "salmon4", "dark slate blue", "DarkSlateBlue", "sea green", "SeaGreen",
                     "SeaGreen4",
                     "SlateBlue4", "gray35", "grey35", "maroon4", "goldenrod4", "gray34", "grey34", "OrangeRed3",
                     "gold4", "red",
                     "red1", "IndianRed4", "VioletRed4", "green", "green1", "blue", "blue1", "gray33", "grey33",
                     "purple4",
                     "brown", "DarkGoldenrod4", "sienna4", "coral4", "firebrick", "gray32", "grey32", "DeepSkyBlue4",
                     "RoyalBlue4",
                     "dark olive green", "DarkOliveGreen", "red2", "green2", "blue2", "gray31", "grey31", "DodgerBlue4",
                     "tomato4",
                     "gray30", "grey30", "orange4", "DeepPink4", "chocolate4", "saddle brown", "SaddleBrown", "gray29",
                     "grey29",
                     "gray28", "grey28", "brown4", "DarkOrange4", "chartreuse4", "SpringGreen4", "gray27", "grey27",
                     "forest green", "ForestGreen", "red3", "dark slate gray", "dark slate grey", "DarkSlateGray",
                     "DarkSlateGrey",
                     "green3", "blue3", "medium blue", "MediumBlue", "gray26", "grey26", "gray25", "grey25",
                     "firebrick4",
                     "gray24", "grey24", "gray23", "grey23", "OrangeRed4", "gray22", "grey22", "gray21", "grey21",
                     "midnight blue",
                     "MidnightBlue", "gray20", "grey20", "gray19", "grey19", "dark red", "DarkRed", "red4", "green4",
                     "blue4",
                     "dark blue", "DarkBlue", "gray18", "grey18", "gray17", "grey17", "navy", "navy blue", "NavyBlue",
                     "gray16",
                     "grey16", "gray15", "grey15", "gray14", "grey14", "dark green", "DarkGreen", "gray13", "grey13",
                     "gray12",
                     "grey12", "gray11", "grey11", "gray10", "grey10", "gray9", "grey9", "gray8", "grey8", "gray7",
                     "grey7",
                     "gray6", "grey6", "gray5", "grey5", "gray4", "grey4", "gray3", "grey3", "gray2", "grey2", "gray1",
                     "grey1",
                     "black", "gray0", "grey0", ]
COLORS_RGB = ["gray100", "grey100", "white", "ivory", "ivory1", "light yellow", "LightYellow", "LightYellow1", "yellow",
              "yellow1", "snow", "snow1", "floral white", "FloralWhite", "lemon chiffon", "LemonChiffon",
              "LemonChiffon1",
              "cornsilk", "cornsilk1", "khaki1", "seashell", "seashell1", "lavender blush", "LavenderBlush",
              "LavenderBlush1", "AntiqueWhite1", "papaya whip", "PapayaWhip", "LightGoldenrod1", "blanched almond",
              "BlanchedAlmond", "wheat1", "misty rose", "MistyRose", "MistyRose1", "bisque", "bisque1", "moccasin",
              "thistle1", "navajo white", "NavajoWhite", "NavajoWhite1", "peach puff", "PeachPuff", "PeachPuff1",
              "gold",
              "gold1", "burlywood1", "RosyBrown1", "goldenrod1", "pink", "plum1", "DarkGoldenrod1", "light pink",
              "LightPink", "pink1", "LightPink1", "tan1", "orange", "orange1", "light salmon", "LightSalmon",
              "LightSalmon1", "salmon1", "dark orange", "DarkOrange", "orchid1", "PaleVioletRed1", "sienna1", "coral",
              "chocolate1", "DarkOrange1", "coral1", "HotPink1", "IndianRed1", "hot pink", "HotPink", "tomato",
              "tomato1",
              "orange red", "OrangeRed", "OrangeRed1", "brown1", "VioletRed1", "maroon1", "firebrick1", "deep pink",
              "DeepPink", "DeepPink1", "magenta", "magenta1", "red", "red1", "old lace", "OldLace", "gray99", "grey99",
              "gray98", "grey98", "light goldenrod yellow", "LightGoldenrodYellow", "linen", "antique white",
              "AntiqueWhite", "salmon", "ghost white", "GhostWhite", "gray97", "grey97", "mint cream", "MintCream",
              "gray96", "grey96", "white smoke", "WhiteSmoke", "beige", "wheat", "sandy brown", "SandyBrown", "gray95",
              "grey95", "azure", "azure1", "honeydew", "honeydew1", "alice blue", "AliceBlue", "gray94", "grey94",
              "khaki",
              "light coral", "LightCoral", "ivory2", "LightYellow2", "yellow2", "snow2", "LemonChiffon2", "cornsilk2",
              "pale goldenrod", "PaleGoldenrod", "khaki2", "seashell2", "LavenderBlush2", "AntiqueWhite2",
              "light goldenrod", "LightGoldenrod", "LightGoldenrod2", "wheat2", "MistyRose2", "bisque2", "thistle2",
              "NavajoWhite2", "PeachPuff2", "gold2", "burlywood2", "RosyBrown2", "goldenrod2", "plum2",
              "DarkGoldenrod2",
              "pink2", "LightPink2", "tan2", "orange2", "LightSalmon2", "violet", "salmon2", "orchid2",
              "PaleVioletRed2",
              "sienna2", "chocolate2", "DarkOrange2", "HotPink2", "coral2", "IndianRed2", "tomato2", "OrangeRed2",
              "brown2",
              "VioletRed2", "maroon2", "firebrick2", "DeepPink2", "magenta2", "red2", "gray93", "grey93", "gray92",
              "grey92", "dark salmon", "DarkSalmon", "gray91", "grey91", "lavender", "gray90", "grey90", "gray89",
              "grey89",
              "light cyan", "LightCyan", "LightCyan1", "azure2", "honeydew2", "gray88", "grey88", "MediumOrchid1",
              "gray87",
              "grey87", "burlywood", "plum", "gainsboro", "gray86", "grey86", "pale violet red", "PaleVioletRed",
              "goldenrod", "orchid", "gray85", "grey85", "thistle", "gray84", "grey84", "gray83", "grey83",
              "light gray",
              "light grey", "LightGray", "LightGrey", "tan", "chocolate", "LightCyan2", "gray82", "grey82",
              "MediumOrchid2",
              "violet red", "VioletRed", "gray81", "grey81", "ivory3", "LightYellow3", "yellow3", "snow3",
              "LemonChiffon3",
              "cornsilk3", "khaki3", "seashell3", "LavenderBlush3", "AntiqueWhite3", "LightGoldenrod3", "wheat3",
              "MistyRose3", "bisque3", "thistle3", "NavajoWhite3", "PeachPuff3", "gold3", "burlywood3", "RosyBrown3",
              "goldenrod3", "plum3", "DarkGoldenrod3", "pink3", "LightPink3", "peru", "tan3", "orange3", "LightSalmon3",
              "salmon3", "orchid3", "PaleVioletRed3", "sienna3", "chocolate3", "DarkOrange3", "HotPink3", "indian red",
              "IndianRed", "coral3", "IndianRed3", "tomato3", "OrangeRed3", "brown3", "VioletRed3", "maroon3",
              "firebrick3",
              "DeepPink3", "magenta3", "red3", "gray80", "grey80", "DarkOliveGreen1", "LightSteelBlue1", "gray79",
              "grey79",
              "gray78", "grey78", "medium violet red", "MediumVioletRed", "SlateGray1", "gray77", "grey77", "gray76",
              "grey76", "DarkSeaGreen1", "azure3", "honeydew3", "OliveDrab1", "LightBlue1", "gray75", "grey75",
              "DarkOrchid1", "gray", "grey", "gray74", "grey74", "dark khaki", "DarkKhaki", "DarkOliveGreen2",
              "LightSteelBlue2", "rosy brown", "RosyBrown", "PaleTurquoise1", "gray73", "grey73", "medium orchid",
              "MediumOrchid", "SlateGray2", "gray72", "grey72", "dark goldenrod", "DarkGoldenrod", "gray71", "grey71",
              "DarkSeaGreen2", "LightCyan3", "MediumOrchid3", "OliveDrab2", "gray70", "grey70", "LightBlue2",
              "DarkOrchid2",
              "firebrick", "LightSkyBlue1", "powder blue", "PowderBlue", "light steel blue", "LightSteelBlue", "gray69",
              "grey69", "maroon", "pale turquoise", "PaleTurquoise", "PaleTurquoise2", "green yellow", "GreenYellow",
              "light blue", "LightBlue", "gray68", "grey68", "gray67", "grey67", "MediumPurple1", "dark gray",
              "dark grey",
              "DarkGray", "DarkGrey", "gray66", "grey66", "gray65", "grey65", "brown", "LightSkyBlue2", "gray64",
              "grey64",
              "DarkOliveGreen3", "LightSteelBlue3", "gray63", "grey63", "sienna", "purple", "SlateGray3",
              "MediumPurple2",
              "gray62", "grey62", "gray61", "grey61", "DarkSeaGreen3", "purple1", "PaleGreen1", "OliveDrab3",
              "yellow green", "YellowGreen", "LightBlue3", "DarkOrchid3", "gray60", "grey60", "dark orchid",
              "DarkOrchid",
              "pale green", "PaleGreen", "CadetBlue1", "DarkSlateGray1", "PaleTurquoise3", "gray59", "grey59", "gray58",
              "grey58", "dark violet", "DarkViolet", "medium purple", "MediumPurple", "gray57", "grey57", "purple2",
              "light green", "LightGreen", "PaleGreen2", "dark sea green", "DarkSeaGreen", "gray56", "grey56",
              "CadetBlue2",
              "DarkSlateGray2", "LightSkyBlue3", "gray55", "grey55", "ivory4", "LightYellow4", "yellow4", "snow4",
              "LemonChiffon4", "cornsilk4", "seashell4", "khaki4", "LavenderBlush4", "AntiqueWhite4", "LightGoldenrod4",
              "wheat4", "MistyRose4", "bisque4", "thistle4", "NavajoWhite4", "PeachPuff4", "gold4", "burlywood4",
              "RosyBrown4", "goldenrod4", "plum4", "DarkGoldenrod4", "pink4", "LightPink4", "tan4", "orange4",
              "LightSalmon4", "salmon4", "orchid4", "PaleVioletRed4", "sienna4", "chocolate4", "saddle brown",
              "SaddleBrown", "DarkOrange4", "coral4", "HotPink4", "IndianRed4", "tomato4", "OrangeRed4", "brown4",
              "VioletRed4", "maroon4", "firebrick4", "DeepPink4", "dark magenta", "DarkMagenta", "magenta4", "dark red",
              "DarkRed", "red4", "gray54", "grey54", "blue violet", "BlueViolet", "MediumPurple3", "SkyBlue1",
              "light sky blue", "LightSkyBlue", "sky blue", "SkyBlue", "gray53", "grey53", "gray52", "grey52",
              "light slate blue", "LightSlateBlue", "azure4", "honeydew4", "SlateBlue1", "gray51", "grey51",
              "aquamarine",
              "aquamarine1", "chartreuse", "chartreuse1", "gray50", "grey50", "SkyBlue2", "gray49", "grey49", "purple3",
              "lawn green", "LawnGreen", "PaleGreen3", "medium slate blue", "MediumSlateBlue", "CadetBlue3",
              "LightCyan4",
              "gray48", "grey48", "SlateBlue2", "MediumOrchid4", "DarkSlateGray3", "gray47", "grey47",
              "light slate gray",
              "light slate grey", "LightSlateGray", "LightSlateGrey", "aquamarine2", "chartreuse2", "gray46", "grey46",
              "gray45", "grey45", "slate gray", "slate grey", "SlateGray", "SlateGrey", "gray44", "grey44",
              "DarkOliveGreen4", "LightSteelBlue4", "gray43", "grey43", "SkyBlue3", "SlateGray4", "olive drab",
              "OliveDrab",
              "gray42", "grey42", "slate blue", "SlateBlue", "DarkSeaGreen4", "OliveDrab4", "dim gray", "dim grey",
              "DimGray", "DimGrey", "gray41", "grey41", "SlateBlue3", "LightBlue4", "DarkOrchid4", "aquamarine3",
              "medium aquamarine", "MediumAquamarine", "chartreuse3", "PaleTurquoise4", "gray40", "grey40",
              "cornflower blue", "CornflowerBlue", "SteelBlue1", "gray39", "grey39", "gray38", "grey38",
              "LightSkyBlue4",
              "cadet blue", "CadetBlue", "gray37", "grey37", "MediumPurple4", "SteelBlue2", "gray36", "grey36",
              "gray35",
              "grey35", "gray34", "grey34", "dark olive green", "DarkOliveGreen", "purple4", "SeaGreen1", "PaleGreen4",
              "gray33", "grey33", "CadetBlue4", "DarkSlateGray4", "gray32", "grey32", "SteelBlue3", "gray31", "grey31",
              "SeaGreen2", "gray30", "grey30", "SkyBlue4", "gray29", "grey29", "medium turquoise", "MediumTurquoise",
              "RoyalBlue1", "dark slate blue", "DarkSlateBlue", "gray28", "grey28", "SlateBlue4", "steel blue",
              "SteelBlue",
              "aquamarine4", "chartreuse4", "gray27", "grey27", "SeaGreen3", "RoyalBlue2", "gray26", "grey26",
              "royal blue",
              "RoyalBlue", "turquoise", "gray25", "grey25", "gray24", "grey24", "medium sea green", "MediumSeaGreen",
              "gray23", "grey23", "RoyalBlue3", "gray22", "grey22", "SteelBlue4", "gray21", "grey21", "gray20",
              "grey20",
              "lime green", "LimeGreen", "gray19", "grey19", "dark slate gray", "dark slate grey", "DarkSlateGray",
              "DarkSlateGrey", "sea green", "SeaGreen", "SeaGreen4", "gray18", "grey18", "gray17", "grey17", "gray16",
              "grey16", "RoyalBlue4", "gray15", "grey15", "gray14", "grey14", "forest green", "ForestGreen", "gray13",
              "grey13", "light sea green", "LightSeaGreen", "gray12", "grey12", "dodger blue", "DodgerBlue",
              "DodgerBlue1",
              "DodgerBlue2", "gray11", "grey11", "gray10", "grey10", "midnight blue", "MidnightBlue", "DodgerBlue3",
              "gray9", "grey9", "gray8", "grey8", "gray7", "grey7", "DodgerBlue4", "gray6", "grey6", "gray5", "grey5",
              "gray4", "grey4", "gray3", "grey3", "gray2", "grey2", "gray1", "grey1", "cyan", "cyan1", "spring green",
              "SpringGreen", "SpringGreen1", "green", "green1", "medium spring green", "MediumSpringGreen",
              "turquoise1",
              "cyan2", "SpringGreen2", "green2", "turquoise2", "dark turquoise", "DarkTurquoise", "cyan3",
              "SpringGreen3",
              "green3", "turquoise3", "deep sky blue", "DeepSkyBlue", "DeepSkyBlue1", "DeepSkyBlue2", "DeepSkyBlue3",
              "cyan4", "dark cyan", "DarkCyan", "SpringGreen4", "green4", "turquoise4", "DeepSkyBlue4", "dark green",
              "DarkGreen", "blue", "blue1", "blue2", "blue3", "medium blue", "MediumBlue", "blue4", "dark blue",
              "DarkBlue",
              "navy", "navy blue", "NavyBlue", "black", "gray0", "grey0", ]
